repos:
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.16.9
        hooks:
            - id: ruff-check
#            - id: ruff-format

    -   repo: https://github.com/PyCQA/flake8
        rev: 7.4.1
        hooks:
            -   id: flake8
                additional_dependencies:
                    - flake8-broken-line==1.0.0
