[project]
name = "git-tag-bump"
dynamic = ["version"]
description = ""
authors = [
    {name = "Dmitry Voronin", email = "dimka665@gmail.com"},
]
license = "MIT"

requires-python = ">=3.10"
dependencies = [
    "typer ~= 0.15",
]

[dependency-groups]
dev = []

[project.scripts]
git-bump = "git_tag_bump:app"

[tool.uv]
preview-features = ["centralized-project-envs"]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
strict = true
latest-tag = true

[tool.hatch.version]
source = "vcs"
raw-options = {local_scheme = "no-local-version"}

[build-system]
#requires = ["poetry-core >= 1.0.0", "poetry-dynamic-versioning"]
#build-backend = "poetry_dynamic_versioning.backend"
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
