[project]
name = "git-tag-bump"
dynamic = ["version"]
description = ""
authors = [
    { name = "Dmitry Voronin", email = "dimka665@gmail.com" },
]
license = "MIT"

requires-python = ">=3.10"
dependencies = [
    "dunamai ~= 1.26.2",
    "typer ~= 0.15",
]

[dependency-groups]
dev = [
    "ipython ~= 8.39.0",
    "pytest ~= 9.1.1",
]

[project.scripts]
git-bump = "git_tag_bump:app"

[tool.uv]
preview-features = ["centralized-project-envs"]

[tool.hatch.version]
source = "vcs"
raw-options = { local_scheme = "no-local-version" }

[build-system]
#requires = ["poetry-core >= 1.0.0", "poetry-dynamic-versioning"]
#build-backend = "poetry_dynamic_versioning.backend"
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "git_tag_bump.py",
    "README.md",
]
